framework:
    messenger:
        transports:
          async: 'amqp://guest:guest@localhost:5672/%2f/messages'
            #async: '%env(MESSENGER_TRANSPORT_DSN)%'
            # failed: 'doctrine://default?queue_name=failed'
        routing:
             'App\Message\PrintingCheck': async
